# Generated by Django 4.2.16 on 2026-07-10 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120, unique=True)),
                ('definition', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('example', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossary_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Glossary Term',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('db_name', models.CharField(max_length=100)),
                ('db_user', models.CharField(blank=True, max_length=100)),
                ('db_host', models.CharField(blank=True, max_length=100)),
                ('db_port', models.CharField(default='5432', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_db_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Year',
                'ordering': ['-year'],
            },
        ),
    ]
