# Generated by Django 5.2.3 on 2026-09-08 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester_section',
            field=models.CharField(blank=True, help_text='Sub-section within department, e.g. Accounts Payable', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester_department',
            field=models.CharField(blank=True, help_text='e.g. Revenue Department, Finance', max_length=100),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('DESKTOP', 'Desktop PC'), ('LAPTOP', 'Laptop'), ('PRINTER', 'Printer'), ('PHONE', 'Phone/VoIP'), ('NETWORK', 'Network Equipment'), ('SERVER', 'Server'), ('MONITOR', 'Monitor'), ('OTHER', 'Other')], default='DESKTOP', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REPAIR', 'Under Repair'), ('RETIRED', 'Retired'), ('MISSING', 'Missing')], default='ACTIVE', max_length=10)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('assigned_to_name', models.CharField(blank=True, max_length=150)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IT Asset',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('RESTORE', 'Restored'), ('DELETE', 'Deleted')], max_length=10)),
                ('status', models.CharField(choices=[('OK', 'Success'), ('FAIL', 'Failed')], default='OK', max_length=6)),
                ('db_name', models.CharField(blank=True, help_text='Database that was backed up', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Backup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('db_name', models.CharField(max_length=100)),
                ('db_user', models.CharField(blank=True, max_length=100)),
                ('db_host', models.CharField(blank=True, max_length=100)),
                ('db_port', models.CharField(default='5432', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_db_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Year',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120, unique=True)),
                ('definition', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('example', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossary_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Glossary Term',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('views', models.PositiveIntegerField(default=0)),
                ('helpful', models.PositiveIntegerField(default=0)),
                ('not_helpful', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to='helpdesk.category')),
            ],
            options={
                'verbose_name': 'KB Article',
                'ordering': ['-views', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(db_index=True, max_length=200)),
                ('field_name', models.CharField(choices=[('title', 'Ticket Title'), ('description', 'Ticket Description'), ('comment', 'Comment / Note'), ('requester_name', 'Requester Name')], db_index=True, max_length=30)),
                ('category', models.CharField(blank=True, db_index=True, help_text='Category slug if phrase is category-specific', max_length=80)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Learned Phrase',
                'ordering': ['-use_count', '-last_used'],
                'unique_together': {('phrase', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Mon…6=Sun', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-28', null=True)),
                ('title_template', models.CharField(max_length=255)),
                ('description_template', models.TextField()),
                ('priority', models.CharField(default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_created_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_assignments', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Ticket',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='fas fa-ticket', max_length=60)),
                ('title_template', models.CharField(max_length=255)),
                ('description_template', models.TextField()),
                ('priority', models.CharField(default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Template',
                'ordering': ['-use_count', 'name'],
            },
        ),
    ]
