# Generated by Django 4.2.16 on 2026-07-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_glossaryterm_databaseyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(db_index=True, max_length=200)),
                ('field_name', models.CharField(choices=[('title', 'Ticket Title'), ('description', 'Ticket Description'), ('comment', 'Comment / Note'), ('requester_name', 'Requester Name')], db_index=True, max_length=30)),
                ('category', models.CharField(blank=True, db_index=True, help_text='Category slug if phrase is category-specific', max_length=80)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Learned Phrase',
                'ordering': ['-use_count', '-last_used'],
                'unique_together': {('phrase', 'field_name')},
            },
        ),
    ]
