# Generated by Django 6.0.7 on 2026-07-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_learnedphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requester_section',
            field=models.CharField(blank=True, help_text='Sub-section within department, e.g. Accounts Payable', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester_department',
            field=models.CharField(blank=True, help_text='e.g. Revenue Department, Finance', max_length=100),
        ),
    ]
