# Generated by Django 4.2.16 on 2026-07-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_insert_categories'),
        ('helpdesk', '0005_insert_categories'),
        ('helpdesk', '0005_insert_helpdesk_categories'),
    ]

    operations = [
    ]
