# Generated by Django 6.1 on 2026-08-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_add_kb_assets_templates_recurring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('RESTORE', 'Restored'), ('DELETE', 'Deleted')], max_length=10)),
                ('status', models.CharField(choices=[('OK', 'Success'), ('FAIL', 'Failed')], default='OK', max_length=6)),
                ('db_name', models.CharField(blank=True, help_text='Database that was backed up', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Backup',
                'ordering': ['-created_at'],
            },
        ),
    ]
