# Generated by Django 4.2.16 on 2026-08-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_add_escalation_pending_notif'),
        ('helpdesk', '0006_merge_20260726_1100'),
    ]

    operations = [
    ]
