# Generated by Django 5.2.3 on 2026-09-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_ticket_escalation_level_and_more'),
        ('helpdesk', '0007_add_database_backup'),
    ]

    operations = [
    ]
