# Generated by Django 5.2.3 on 2026-08-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_add_database_backup'),
        ('helpdesk', '0007_merge_20260824_1601'),
    ]

    operations = [
    ]
