# Generated by Django 4.2.16 on 2026-06-26 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('last_call', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_number', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoIPProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=5060)),
                ('protocol', models.CharField(choices=[('SIP', 'SIP'), ('IAX2', 'IAX2'), ('H323', 'H.323'), ('WebRTC', 'WebRTC')], default='SIP', max_length=10)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoIPCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('caller_number', models.CharField(help_text='Caller ID / phone number', max_length=50)),
                ('caller_name', models.CharField(blank=True, help_text='Caller ID name if provided', max_length=150)),
                ('destination_number', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('INTERNAL', 'Internal')], default='INBOUND', max_length=10)),
                ('status', models.CharField(choices=[('RINGING', 'Ringing'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('FAILED', 'Failed'), ('VOICEMAIL', 'Voicemail')], default='RINGING', max_length=10)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ring_duration_seconds', models.PositiveIntegerField(default=0)),
                ('talk_duration_seconds', models.PositiveIntegerField(default=0)),
                ('hold_duration_seconds', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_path', models.CharField(blank=True, max_length=500)),
                ('transferred_to', models.CharField(blank=True, max_length=50)),
                ('disposition_code', models.CharField(blank=True, help_text='Resolution code e.g. RESOLVED, TRANSFERRED', max_length=50)),
                ('ticket_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls_answered', to=settings.AUTH_USER_MODEL)),
                ('caller_extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_calls', to='voip.extension')),
                ('destination_extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_calls', to='voip.extension')),
                ('voip_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voip.voipprovider')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddField(
            model_name='extension',
            name='voip_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voip.voipprovider'),
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INITIATED', 'Call Initiated'), ('ANSWERED', 'Call Answered'), ('HOLD', 'Put on Hold'), ('UNHOLD', 'Resumed from Hold'), ('TRANSFER', 'Transferred'), ('ENDED', 'Call Ended'), ('MISSED', 'Call Missed')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='voip.voipcall')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='voipcall',
            index=models.Index(fields=['caller_number'], name='voip_voipca_caller__5450c5_idx'),
        ),
        migrations.AddIndex(
            model_name='voipcall',
            index=models.Index(fields=['status'], name='voip_voipca_status_6f644e_idx'),
        ),
        migrations.AddIndex(
            model_name='voipcall',
            index=models.Index(fields=['initiated_at'], name='voip_voipca_initiat_322331_idx'),
        ),
    ]
