# Generated by Django 6.1 on 2026-08-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_add_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_embedding',
            field=models.TextField(blank=True, help_text='JSON list of averaged face embeddings from enrollment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face_fail_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive failed face verifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face_locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked after too many face failures', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face_mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Master switch — both face and TOTP off if False'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_backup_codes',
            field=models.TextField(blank=True, help_text='JSON list of one-time backup codes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Base32 TOTP secret key', max_length=64),
        ),
    ]
