# Generated by Django 6.1 on 2026-08-30 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_mfa_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('FACE', 'Face Recognition'), ('TOTP', 'Authenticator App'), ('BACKUP', 'Backup Code')], max_length=10)),
                ('result', models.CharField(choices=[('PASS', 'Passed'), ('FAIL', 'Failed'), ('LOCKED', 'Account Locked')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('confidence', models.FloatField(blank=True, help_text='Face match confidence 0-1', null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
