# Generated by Django 6.1 on 2026-08-30 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_mfa_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='User has accepted the system T&C'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Version of T&C accepted', max_length=10),
        ),
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g. 1.0, 1.1, 2.0', max_length=10, unique=True)),
                ('title', models.CharField(default='BeitDesk System Terms & Conditions', max_length=200)),
                ('content', models.TextField(help_text='Full T&C text (plain text or HTML)')),
                ('is_current', models.BooleanField(default=False, help_text='Only one version can be current')),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms Version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.termsversion')),
            ],
            options={
                'verbose_name': 'T&C Acceptance Record',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
